name: nizhib

services:
  traefik:
    image: traefik:v3.3
    command:
      - --log.level=INFO
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      nizhib:
        aliases:
          - portrait.localhost
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.localhost`)
      - traefik.http.routers.api.entrypoints=http
      - traefik.http.routers.api.service=api@internal

  portrait-front:
    build:
      context: front
      dockerfile: Dockerfile
    networks:
      - nizhib
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.portrait-front.rule=Host(`portrait.localhost`)
      - traefik.http.routers.portrait-front.entrypoints=http

  portrait-back:
    build:
      context: back
      dockerfile: Dockerfile
    networks:
      - nizhib
    expose:
      - 5000
    labels:
      - traefik.enable=true
      - traefik.http.routers.portrait-back.rule=Host(`portrait.localhost`) && PathPrefix(`/api`)
      - traefik.http.routers.portrait-back.entrypoints=http
      - traefik.http.routers.portrait-back.middlewares=remove-api
      - traefik.http.middlewares.remove-api.stripprefix.prefixes=/api

networks:
  nizhib:
    name: nizhib
