name: nizhib

services:
  portrait-front:
    build:
      context: front
      dockerfile: Dockerfile
    networks:
      - nizhib
    expose:
      - 3000
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.portrait-front.rule=Host(`portrait.nizhib.ai`)
      - traefik.http.routers.portrait-front.entrypoints=https
      - traefik.http.routers.portrait-front.tls.certresolver=nizhib

  portrait-back:
    build:
      context: back
      dockerfile: Dockerfile
    networks:
      - nizhib
    expose:
      - 5000
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.portrait-back.rule=Host(`portrait.nizhib.ai`) && PathPrefix(`/api`)
      - traefik.http.routers.portrait-back.entrypoints=https
      - traefik.http.routers.portrait-back.tls.certresolver=nizhib
      - traefik.http.routers.portrait-back.middlewares=remove-api
      - traefik.http.middlewares.remove-api.stripprefix.prefixes=/api

networks:
  nizhib:
    name: nizhib
